/*
 * Kaia Mac
 * Super String Software
 * November 7, 2018
 */

/**
 *
 * @author kamac8665
 */
public class FormSuperStringSoftware extends javax.swing.JFrame {

    /**
     * Creates new form FormSuperStringSoftware
     */
    public FormSuperStringSoftware() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        lengthProgram = new javax.swing.JPanel();
        lengthProgramInfo = new javax.swing.JLabel();
        lengthProgramInput = new javax.swing.JTextField();
        lengthProgramButton = new javax.swing.JButton();
        lengthProgramOutput = new javax.swing.JLabel();
        capitalizeProgram = new javax.swing.JPanel();
        capitalizeProgramInfo = new javax.swing.JLabel();
        capitalizeProgramInput = new javax.swing.JTextField();
        capitalizeProgramButton = new javax.swing.JButton();
        capitalizeProgramOutput = new javax.swing.JLabel();
        fourthProgram = new javax.swing.JPanel();
        fourthProgramInfo = new javax.swing.JLabel();
        fourthProgramInput = new javax.swing.JTextField();
        fourthProgramButton = new javax.swing.JButton();
        fourthProgramOutput = new javax.swing.JLabel();
        identicalProgram = new javax.swing.JPanel();
        identicalProgramInfo = new javax.swing.JLabel();
        identicalProgramInput1 = new javax.swing.JTextField();
        identicalProgramInput2 = new javax.swing.JTextField();
        identicalProgramButton = new javax.swing.JButton();
        identicalProgramOutput = new javax.swing.JLabel();
        foundLetterProgram = new javax.swing.JPanel();
        foundLetterProgramInfo = new javax.swing.JLabel();
        foundLetterProgramInput1 = new javax.swing.JTextField();
        foundLetterProgramInput2 = new javax.swing.JTextField();
        foundLetterProgramButton = new javax.swing.JButton();
        foundLetterProgramOutput = new javax.swing.JLabel();
        fourToSixProgram = new javax.swing.JPanel();
        fourToSixProgramInfo = new javax.swing.JLabel();
        fourToSixProgramInput = new javax.swing.JTextField();
        fourToSixProgramButton = new javax.swing.JButton();
        fourToSixProgramOutputchar1 = new javax.swing.JLabel();
        fourToSixProgramOutputchar2 = new javax.swing.JLabel();
        fourToSixProgramOutputchar3 = new javax.swing.JLabel();
        replaceProgram = new javax.swing.JPanel();
        replaceProgramInfo = new javax.swing.JLabel();
        replaceProgramInput = new javax.swing.JTextField();
        replaceProgramButton = new javax.swing.JButton();
        replaceProgramOutput = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        titleLabel.setText("SUPER STRING SOFTWARE");

        lengthProgram.setBackground(new java.awt.Color(204, 204, 255));

        lengthProgramInfo.setText("Enter a string. The program will output the number of characters in the string:");

        lengthProgramButton.setText("Length");
        lengthProgramButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lengthProgramButtonActionPerformed(evt);
            }
        });

        lengthProgramOutput.setText("---");

        javax.swing.GroupLayout lengthProgramLayout = new javax.swing.GroupLayout(lengthProgram);
        lengthProgram.setLayout(lengthProgramLayout);
        lengthProgramLayout.setHorizontalGroup(
            lengthProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lengthProgramLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lengthProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lengthProgramInfo)
                    .addGroup(lengthProgramLayout.createSequentialGroup()
                        .addComponent(lengthProgramInput, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lengthProgramButton)
                        .addGap(18, 18, 18)
                        .addComponent(lengthProgramOutput)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lengthProgramLayout.setVerticalGroup(
            lengthProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lengthProgramLayout.createSequentialGroup()
                .addComponent(lengthProgramInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lengthProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lengthProgramInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lengthProgramButton)
                    .addComponent(lengthProgramOutput)))
        );

        capitalizeProgram.setBackground(new java.awt.Color(204, 204, 255));

        capitalizeProgramInfo.setText("Enter a string using lowercase letters. The program will output string in all capital letters:");

        capitalizeProgramButton.setText("All Caps");
        capitalizeProgramButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capitalizeProgramButtonActionPerformed(evt);
            }
        });

        capitalizeProgramOutput.setText("---");

        javax.swing.GroupLayout capitalizeProgramLayout = new javax.swing.GroupLayout(capitalizeProgram);
        capitalizeProgram.setLayout(capitalizeProgramLayout);
        capitalizeProgramLayout.setHorizontalGroup(
            capitalizeProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(capitalizeProgramLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(capitalizeProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(capitalizeProgramInfo)
                    .addGroup(capitalizeProgramLayout.createSequentialGroup()
                        .addComponent(capitalizeProgramInput, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(capitalizeProgramButton)
                        .addGap(18, 18, 18)
                        .addComponent(capitalizeProgramOutput)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        capitalizeProgramLayout.setVerticalGroup(
            capitalizeProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(capitalizeProgramLayout.createSequentialGroup()
                .addComponent(capitalizeProgramInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(capitalizeProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(capitalizeProgramInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(capitalizeProgramButton)
                    .addComponent(capitalizeProgramOutput)))
        );

        fourthProgram.setBackground(new java.awt.Color(204, 204, 255));

        fourthProgramInfo.setText("Enter a string. The program will output the character at the 4th spot:");

        fourthProgramButton.setText("4th Spot");
        fourthProgramButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourthProgramButtonActionPerformed(evt);
            }
        });

        fourthProgramOutput.setText("---");

        javax.swing.GroupLayout fourthProgramLayout = new javax.swing.GroupLayout(fourthProgram);
        fourthProgram.setLayout(fourthProgramLayout);
        fourthProgramLayout.setHorizontalGroup(
            fourthProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fourthProgramLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fourthProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fourthProgramInfo)
                    .addGroup(fourthProgramLayout.createSequentialGroup()
                        .addComponent(fourthProgramInput, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fourthProgramButton)
                        .addGap(18, 18, 18)
                        .addComponent(fourthProgramOutput)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fourthProgramLayout.setVerticalGroup(
            fourthProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fourthProgramLayout.createSequentialGroup()
                .addComponent(fourthProgramInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fourthProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fourthProgramInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fourthProgramOutput)
                    .addComponent(fourthProgramButton)))
        );

        identicalProgram.setBackground(new java.awt.Color(204, 204, 255));

        identicalProgramInfo.setText("Enter two strings. The program will output whether or not they are identical:");

        identicalProgramButton.setText("Identical?");
        identicalProgramButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identicalProgramButtonActionPerformed(evt);
            }
        });

        identicalProgramOutput.setText("---");

        javax.swing.GroupLayout identicalProgramLayout = new javax.swing.GroupLayout(identicalProgram);
        identicalProgram.setLayout(identicalProgramLayout);
        identicalProgramLayout.setHorizontalGroup(
            identicalProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(identicalProgramLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(identicalProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(identicalProgramLayout.createSequentialGroup()
                        .addComponent(identicalProgramInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(identicalProgramInput2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(identicalProgramButton)
                        .addGap(18, 18, 18)
                        .addComponent(identicalProgramOutput)
                        .addGap(24, 24, 24))
                    .addGroup(identicalProgramLayout.createSequentialGroup()
                        .addComponent(identicalProgramInfo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        identicalProgramLayout.setVerticalGroup(
            identicalProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(identicalProgramLayout.createSequentialGroup()
                .addComponent(identicalProgramInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(identicalProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(identicalProgramInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(identicalProgramButton)
                    .addComponent(identicalProgramOutput)
                    .addComponent(identicalProgramInput2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        foundLetterProgram.setBackground(new java.awt.Color(204, 204, 255));

        foundLetterProgramInfo.setText("Enter a string and a letter. The program will output whether the letter is found in the string:");

        foundLetterProgramButton.setText("Letter Found?");
        foundLetterProgramButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foundLetterProgramButtonActionPerformed(evt);
            }
        });

        foundLetterProgramOutput.setText("---");

        javax.swing.GroupLayout foundLetterProgramLayout = new javax.swing.GroupLayout(foundLetterProgram);
        foundLetterProgram.setLayout(foundLetterProgramLayout);
        foundLetterProgramLayout.setHorizontalGroup(
            foundLetterProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(foundLetterProgramLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(foundLetterProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(foundLetterProgramLayout.createSequentialGroup()
                        .addComponent(foundLetterProgramInfo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(foundLetterProgramLayout.createSequentialGroup()
                        .addComponent(foundLetterProgramInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(foundLetterProgramInput2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(foundLetterProgramButton)
                        .addGap(18, 18, 18)
                        .addComponent(foundLetterProgramOutput)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        foundLetterProgramLayout.setVerticalGroup(
            foundLetterProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(foundLetterProgramLayout.createSequentialGroup()
                .addComponent(foundLetterProgramInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(foundLetterProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foundLetterProgramInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(foundLetterProgramButton)
                    .addComponent(foundLetterProgramOutput)
                    .addComponent(foundLetterProgramInput2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        fourToSixProgram.setBackground(new java.awt.Color(204, 204, 255));

        fourToSixProgramInfo.setText("Enter a string that is at least 8 characters long. The program will output characters 4 to 6:");

        fourToSixProgramButton.setText("Characters 4 to 6");
        fourToSixProgramButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourToSixProgramButtonActionPerformed(evt);
            }
        });

        fourToSixProgramOutputchar1.setText("---");

        fourToSixProgramOutputchar2.setText("---");

        fourToSixProgramOutputchar3.setText("---");

        javax.swing.GroupLayout fourToSixProgramLayout = new javax.swing.GroupLayout(fourToSixProgram);
        fourToSixProgram.setLayout(fourToSixProgramLayout);
        fourToSixProgramLayout.setHorizontalGroup(
            fourToSixProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fourToSixProgramLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fourToSixProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fourToSixProgramInfo)
                    .addGroup(fourToSixProgramLayout.createSequentialGroup()
                        .addComponent(fourToSixProgramInput, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fourToSixProgramButton)
                        .addGap(18, 18, 18)
                        .addComponent(fourToSixProgramOutputchar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fourToSixProgramOutputchar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fourToSixProgramOutputchar3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fourToSixProgramLayout.setVerticalGroup(
            fourToSixProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fourToSixProgramLayout.createSequentialGroup()
                .addComponent(fourToSixProgramInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fourToSixProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fourToSixProgramInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fourToSixProgramButton)
                    .addComponent(fourToSixProgramOutputchar1)
                    .addComponent(fourToSixProgramOutputchar2)
                    .addComponent(fourToSixProgramOutputchar3))
                .addGap(40, 40, 40))
        );

        replaceProgram.setBackground(new java.awt.Color(204, 204, 255));

        replaceProgramInfo.setText("Enter a string that contains at least one 'a'. The program will replace all occurances of 'a':");

        replaceProgramButton.setText("Replaces 'a'");
        replaceProgramButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replaceProgramButtonActionPerformed(evt);
            }
        });

        replaceProgramOutput.setText("---");

        javax.swing.GroupLayout replaceProgramLayout = new javax.swing.GroupLayout(replaceProgram);
        replaceProgram.setLayout(replaceProgramLayout);
        replaceProgramLayout.setHorizontalGroup(
            replaceProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(replaceProgramLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(replaceProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(replaceProgramInfo)
                    .addGroup(replaceProgramLayout.createSequentialGroup()
                        .addComponent(replaceProgramInput, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(replaceProgramButton)
                        .addGap(18, 18, 18)
                        .addComponent(replaceProgramOutput)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        replaceProgramLayout.setVerticalGroup(
            replaceProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(replaceProgramLayout.createSequentialGroup()
                .addComponent(replaceProgramInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(replaceProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(replaceProgramInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(replaceProgramButton)
                    .addComponent(replaceProgramOutput)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleLabel)
                .addGap(80, 80, 80))
            .addComponent(lengthProgram, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(capitalizeProgram, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fourthProgram, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(identicalProgram, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(foundLetterProgram, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fourToSixProgram, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(replaceProgram, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lengthProgram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(capitalizeProgram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fourthProgram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(identicalProgram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(foundLetterProgram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fourToSixProgram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(replaceProgram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lengthProgramButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lengthProgramButtonActionPerformed
        //get text
        String userinput = lengthProgramInput.getText();
        //set text
        lengthProgramOutput.setText("There is " + userinput.length() + " characters.");
    }//GEN-LAST:event_lengthProgramButtonActionPerformed

    private void capitalizeProgramButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capitalizeProgramButtonActionPerformed
        //get text
        String userinput = capitalizeProgramInput.getText();
        //set text
        capitalizeProgramOutput.setText(userinput.toUpperCase());
    }//GEN-LAST:event_capitalizeProgramButtonActionPerformed

    private void fourthProgramButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourthProgramButtonActionPerformed
        //get text
        String userinput = fourthProgramInput.getText();
        //set text
        fourthProgramOutput.setText("The fourth character is ' " + (userinput.charAt(3)) + " '.");
    }//GEN-LAST:event_fourthProgramButtonActionPerformed

    private void identicalProgramButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identicalProgramButtonActionPerformed
        //get text
        String userinput1 = identicalProgramInput1.getText();
        String userinput2 = identicalProgramInput2.getText();
        //set text
        if(userinput1.equalsIgnoreCase(userinput2))
        {
            identicalProgramOutput.setText("They are identical.");
        }
        else
        {
            identicalProgramOutput.setText("They are not identical.");
        }    
    }//GEN-LAST:event_identicalProgramButtonActionPerformed

    private void foundLetterProgramButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foundLetterProgramButtonActionPerformed
        //get text
        String userinput1 = foundLetterProgramInput1.getText();
        String userinput2 = foundLetterProgramInput2.getText();
        //set text
        if(userinput1.contains(userinput2))
        {
            foundLetterProgramOutput.setText("Letter found.");
        }
        else
        {
            foundLetterProgramOutput.setText("Letter not found.");
        }
    }//GEN-LAST:event_foundLetterProgramButtonActionPerformed

    private void fourToSixProgramButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourToSixProgramButtonActionPerformed
        //get text
        String userinput = fourToSixProgramInput.getText();
        //set text
        fourToSixProgramOutputchar1.setText(" " + (userinput.charAt(3)));
        fourToSixProgramOutputchar2.setText(" " + (userinput.charAt(4)));
        fourToSixProgramOutputchar3.setText(" " + (userinput.charAt(5)));
    }//GEN-LAST:event_fourToSixProgramButtonActionPerformed

    private void replaceProgramButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replaceProgramButtonActionPerformed
        //get text
        String userinput = replaceProgramInput.getText();
        //set text
        replaceProgramOutput.setText((userinput.replace("a", "x")));
    }//GEN-LAST:event_replaceProgramButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSuperStringSoftware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSuperStringSoftware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSuperStringSoftware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSuperStringSoftware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSuperStringSoftware().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel capitalizeProgram;
    private javax.swing.JButton capitalizeProgramButton;
    private javax.swing.JLabel capitalizeProgramInfo;
    private javax.swing.JTextField capitalizeProgramInput;
    private javax.swing.JLabel capitalizeProgramOutput;
    private javax.swing.JPanel foundLetterProgram;
    private javax.swing.JButton foundLetterProgramButton;
    private javax.swing.JLabel foundLetterProgramInfo;
    private javax.swing.JTextField foundLetterProgramInput1;
    private javax.swing.JTextField foundLetterProgramInput2;
    private javax.swing.JLabel foundLetterProgramOutput;
    private javax.swing.JPanel fourToSixProgram;
    private javax.swing.JButton fourToSixProgramButton;
    private javax.swing.JLabel fourToSixProgramInfo;
    private javax.swing.JTextField fourToSixProgramInput;
    private javax.swing.JLabel fourToSixProgramOutputchar1;
    private javax.swing.JLabel fourToSixProgramOutputchar2;
    private javax.swing.JLabel fourToSixProgramOutputchar3;
    private javax.swing.JPanel fourthProgram;
    private javax.swing.JButton fourthProgramButton;
    private javax.swing.JLabel fourthProgramInfo;
    private javax.swing.JTextField fourthProgramInput;
    private javax.swing.JLabel fourthProgramOutput;
    private javax.swing.JPanel identicalProgram;
    private javax.swing.JButton identicalProgramButton;
    private javax.swing.JLabel identicalProgramInfo;
    private javax.swing.JTextField identicalProgramInput1;
    private javax.swing.JTextField identicalProgramInput2;
    private javax.swing.JLabel identicalProgramOutput;
    private javax.swing.JPanel lengthProgram;
    private javax.swing.JButton lengthProgramButton;
    private javax.swing.JLabel lengthProgramInfo;
    private javax.swing.JTextField lengthProgramInput;
    private javax.swing.JLabel lengthProgramOutput;
    private javax.swing.JPanel replaceProgram;
    private javax.swing.JButton replaceProgramButton;
    private javax.swing.JLabel replaceProgramInfo;
    private javax.swing.JTextField replaceProgramInput;
    private javax.swing.JLabel replaceProgramOutput;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
